### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by Michael-F-Bryan** [HadrienG2/3photons-rust#1]
Couldn't you avoid that big match statement in your `main()` function by adding a suitable implementation for `Display`  on your error type? 

You may also want to implement `std::error::Error` on each of the error types as well. Otherwise I know [error-chain] is a well accepted tool to use for doing error handling nicely.

[error-chain]: http://brson.github.io/2016/11/30/starting-with-error-chain

**Comment by Michael-F-Bryan** [comment]
Oops, I'm reading this from a phone so I didn't realise this was a fork of an existing project. Feel free to ignore this issue and close it if you feel it's not relevant.

**Comment by HadrienG2** [comment]
It's okay, I intend to keep the repos in sync :)

**Comment by HadrienG2** [comment]
Okay, this is done in the latest master.

error-chain is one of these things which I continuously procrastinated learning because it looks like WAY too much brittle macro black magic for my taste. But it turned out to work well enough in the end :)
