### ISSUE TITLE
Generate numerical prefix operators using macros

### ISSUE THREAD

**Issue by HadrienG2** [HadrienG2/3photons-rust#3]
The repetition... it burns!

**Comment by HadrienG2** [comment]
Done in the latest master.

**Comment by mxxo** [comment]
What do you think about factoring these out into a small crate? The code is pretty trivial but maybe not obvious for beginners. 

Someone just getting started might be turned off right away by `x.sin()`, especially if there isn't a quick solution (like you mentioned over [here](https://gist.github.com/HadrienG2/e9a875bdf98b528594f4e20f8176bb68)).

**Comment by HadrienG2** [comment]
One small obstacle to generalizing this into a separate crate is that right now, I'm assuming that there is a single Float type. Whereas for a dedicated crate, there would be an expectation of supporting both `f32` and `f64`.

But from a quick look at the num crate's `Float` trait, it does seem to have everything I need to resolve this issue.

**Comment by HadrienG2** [comment]
Alright, I tried to give this a spin and the result actually looks pretty promising. If everything goes well, I should be able to publish a crate tomorrow.

**Comment by HadrienG2** [comment]
There you go: https://github.com/HadrienG2/prefix_num_ops .

**Comment by mxxo** [comment]
Nicely done! That looks really good :)
